### ISSUE TITLE
Vuedraggable

### ISSUE THREAD

**Issue by AbdullahBakir97** [AbdullahBakir97/Project-Management-Tool#1]
ERROR
Cannot read properties of undefined (reading 'header')
TypeError: Cannot read properties of undefined (reading 'header')
    at getSlot (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2006:34)
    at computeChildrenAndOffsets (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2012:16)
    at Proxy.render (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2121:33)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1028:16)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6125:46)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:221:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6256:16)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6266:5)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6034:7)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5988:9)

ERROR
Cannot read properties of undefined (reading 'header')
TypeError: Cannot read properties of undefined (reading 'header')
    at getSlot (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2006:34)
    at computeChildrenAndOffsets (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2012:16)
    at Proxy.render (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2121:33)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1028:16)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6125:46)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:221:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6256:16)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6266:5)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6034:7)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5988:9)

ERROR
Cannot read properties of undefined (reading 'header')
TypeError: Cannot read properties of undefined (reading 'header')
    at getSlot (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2006:34)
    at computeChildrenAndOffsets (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2012:16)
    at Proxy.render (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:2121:33)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1028:16)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6125:46)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:221:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6256:16)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6266:5)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6034:7)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5988:9)

**Comment by kingshadow98** [comment]
same problem
